### ISSUE TITLE
I couldn't find the build output

### ISSUE THREAD

**Issue by rigille** [StratusFearMe21/cargo-appimage#18] opened 2022-04-27 12:18 UTC
Hey I followed the installation steps, `appimagetool` is in my path:
```
rigille@altissa:~$ appimagetool --version
appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
```
I did put
```
[package.metadata.appimage]
auto_link = true
```
inside my `Cargo.toml`. I can also run `cargo appimage` without errors, but after that the result looks exactly the same as running `cargo build --release`. I'm using Ubuntu 21.10. What could be the problem?

**Comment by StratusFearMe21** [comment] 2022-04-29 01:38
The finished appimage should be put in wherever the current working directory is, and build file can be found at `./target/{crate_name}.AppDir`

**Comment by StratusFearMe21** [comment] 2022-04-29 01:39
other than that, I don't know why it's not building. Are you sure it didn't produce any errors?

**Comment by korejan** [comment] 2022-04-30 21:02
I think I'm having the same problem. I just started to use to today so I don't know what to expect but I get no error messages and the output looks like a normal cargo build. I also tried adding `-vv` flag, didn't see anything wrong.

**Comment by elkowar** [comment] 2022-05-26 12:12
same here - might the issue be related to being in a cargo workspace?

**Comment by 13hannes11** [comment] 2022-06-04 11:54
I have the same issue. To reproduce you can use this project https://github.com/13hannes11/gtk4-rs-docker. Navigate to `appimage` and run `docker-compose up`. The build process succeeds but doesn't produce an AppImage file.

**Comment by 13hannes11** [comment] 2022-06-04 12:42
I found that rebuilding the 1.59 image also results in the same issue. If I base the image of gtk4-rs-docker on fedora:35 instead of latest it still does not work.

**Comment by tobealive** [comment] 2022-08-13 13:05
> @StratusFearMe21 I think I'm having the same problem. I just started to use it today so I don't know what to expect but I get no error messages and the output looks like a normal cargo build. I also tried adding -vv flag, didn't see anything wrong.

same.

**Comment by rhelmot** [comment] 2022-08-19 19:30
I ran into this issue and discovered the cause and fix: you must have your build target declared in cargo.toml, you can't simply use the implicit main.rs bin target.

Add the following to your cargo.toml:

```
[[bin]]
name = "my_crate"
path = "src/main.rs"
```

I would consider this a bug that should be fixed.

**Comment by StratusFearMe21** [comment] 2023-06-27 21:05
Im so sorry about this, I haven't touched this crate in far too long. This is fixed

**Comment by StratusFearMe21** [comment] 2023-06-27 21:14
I've just pushed an update to crates.io

**Closed** 2024-02-27 16:07 UTC
